Router.map ->
  @route "interfaceComponents", path: "/interface-components"
  @route "visuals", path: "/interface-components/visuals"
  @route "navs", path: "/interface-components/navs"
  @route "panelOptions", path: "/interface-components/panel-options"
  @route "navbars", path: "/interface-components/navbars"
  @route "infoBlocks", path: "/interface-components/info-blocks"
  @route "icons", path: "/interface-components/icons"
  @route "buttons", path: "/interface-components/buttons"
  @route "calendar", path: "/interface-components/calendar"
  @route "typography", path: "/interface-components/typography"
  @route "gallery", path: "/interface-components/gallery"
  @route "headerElements", path: "/interface-components/header-elements"
  @route "contentGrid", path: "/interface-components/content-grid"